name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lumen-tests:
    runs-on: ubuntu-20.04
    strategy:
        matrix:
          php-versions: ['7.4']
          phpunit-versions: ['latest']

    steps:
    - run: |
          sudo systemctl start mysql
          mysql -e 'CREATE DATABASE test;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Prepare Lumen
      run: |
        php artisan key:generate
        php artisan migrate
    - name: Execute test
      run: vendor/bin/phpunit