name: Tests
on:   
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lumen-tests:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4

    strategy:
      matrix:
        php-versions: ['8.0','8.1']
        phpunit-versions: ['latest']
  
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdb
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install --no-scripts
     
      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: run tests
        run: vendor/bin/phpunit
